language: c

compiler:
  - clang
  - gcc

services:
  - docker

before_install:
  - docker pull epitechcontent/epitest-docker
  - docker run -v `pwd`:/project -it epitechcontent/epitest-docker /bin/bash -c "cd project && make"

scrip:
  - make